// <auto-generated />
using System;
using BinTool.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BinTool.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260731115638_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("BinTool.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BinTool.Core.Entities.AuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedProperties")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientInfo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AuditEntry_UserId");

                    b.HasIndex("EntityType", "Timestamp")
                        .HasDatabaseName("IX_AuditEntry_Type_Timestamp");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("BinTool.Core.Entities.BinRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("FundingType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Scheme")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Prefix")
                        .IsUnique();

                    b.HasIndex("Prefix", "Scheme")
                        .HasDatabaseName("IX_BinRange_Prefix_Scheme");

                    b.ToTable("BinRanges", (string)null);
                });

            modelBuilder.Entity("BinTool.Core.Entities.CommissionRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FixedAmount")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinimumFee")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PercentageRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Scheme")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_CommissionRule_Active");

                    b.HasIndex("RegionId");

                    b.HasIndex("Scheme", "ProductType", "RegionId", "ValidFrom", "ValidTo")
                        .HasDatabaseName("IX_CommissionRule_Lookup");

                    b.ToTable("CommissionRules", (string)null);
                });

            modelBuilder.Entity("BinTool.Core.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("RegionId");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "BG",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7268),
                            Name = "Bulgaria",
                            RegionId = 1,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7268)
                        },
                        new
                        {
                            Id = 2,
                            Code = "AT",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7271),
                            Name = "Austria",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7271)
                        },
                        new
                        {
                            Id = 3,
                            Code = "BE",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7273),
                            Name = "Belgium",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7273)
                        },
                        new
                        {
                            Id = 4,
                            Code = "HR",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7275),
                            Name = "Croatia",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7275)
                        },
                        new
                        {
                            Id = 5,
                            Code = "CY",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7277),
                            Name = "Cyprus",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7277)
                        },
                        new
                        {
                            Id = 6,
                            Code = "CZ",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7279),
                            Name = "Czech Republic",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7279)
                        },
                        new
                        {
                            Id = 7,
                            Code = "DK",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7281),
                            Name = "Denmark",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7281)
                        },
                        new
                        {
                            Id = 8,
                            Code = "EE",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7347),
                            Name = "Estonia",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7347)
                        },
                        new
                        {
                            Id = 9,
                            Code = "FI",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7349),
                            Name = "Finland",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7349)
                        },
                        new
                        {
                            Id = 10,
                            Code = "FR",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7351),
                            Name = "France",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7351)
                        },
                        new
                        {
                            Id = 11,
                            Code = "DE",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7353),
                            Name = "Germany",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7353)
                        },
                        new
                        {
                            Id = 12,
                            Code = "GR",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7355),
                            Name = "Greece",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7355)
                        },
                        new
                        {
                            Id = 13,
                            Code = "HU",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7356),
                            Name = "Hungary",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7357)
                        },
                        new
                        {
                            Id = 14,
                            Code = "IE",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7358),
                            Name = "Ireland",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7359)
                        },
                        new
                        {
                            Id = 15,
                            Code = "IT",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7360),
                            Name = "Italy",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7360)
                        },
                        new
                        {
                            Id = 16,
                            Code = "LV",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7362),
                            Name = "Latvia",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7362)
                        },
                        new
                        {
                            Id = 17,
                            Code = "LT",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7364),
                            Name = "Lithuania",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7364)
                        },
                        new
                        {
                            Id = 18,
                            Code = "LU",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7366),
                            Name = "Luxembourg",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7366)
                        },
                        new
                        {
                            Id = 19,
                            Code = "MT",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7367),
                            Name = "Malta",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7368)
                        },
                        new
                        {
                            Id = 20,
                            Code = "NL",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7369),
                            Name = "Netherlands",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7370)
                        },
                        new
                        {
                            Id = 21,
                            Code = "PL",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7371),
                            Name = "Poland",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7372)
                        },
                        new
                        {
                            Id = 22,
                            Code = "PT",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7373),
                            Name = "Portugal",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7374)
                        },
                        new
                        {
                            Id = 23,
                            Code = "RO",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7375),
                            Name = "Romania",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7375)
                        },
                        new
                        {
                            Id = 24,
                            Code = "SK",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7377),
                            Name = "Slovakia",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7377)
                        },
                        new
                        {
                            Id = 25,
                            Code = "SI",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7378),
                            Name = "Slovenia",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7379)
                        },
                        new
                        {
                            Id = 26,
                            Code = "ES",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7380),
                            Name = "Spain",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7381)
                        },
                        new
                        {
                            Id = 27,
                            Code = "SE",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7382),
                            Name = "Sweden",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7382)
                        },
                        new
                        {
                            Id = 28,
                            Code = "GB",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7384),
                            Name = "United Kingdom",
                            RegionId = 3,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7384)
                        },
                        new
                        {
                            Id = 29,
                            Code = "US",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7386),
                            Name = "United States",
                            RegionId = 3,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7386)
                        },
                        new
                        {
                            Id = 30,
                            Code = "CA",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7388),
                            Name = "Canada",
                            RegionId = 3,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7388)
                        },
                        new
                        {
                            Id = 31,
                            Code = "JP",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7389),
                            Name = "Japan",
                            RegionId = 3,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7390)
                        },
                        new
                        {
                            Id = 32,
                            Code = "CN",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7391),
                            Name = "China",
                            RegionId = 3,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7391)
                        },
                        new
                        {
                            Id = 33,
                            Code = "IN",
                            CreatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7393),
                            Name = "India",
                            RegionId = 3,
                            UpdatedAt = new DateTime(2026, 7, 31, 11, 56, 38, 25, DateTimeKind.Utc).AddTicks(7393)
                        });
                });

            modelBuilder.Entity("BinTool.Core.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("Regions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Domestic transactions (same country)",
                            Name = "Domestic",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Transactions within European Economic Area (subject to interchange caps)",
                            Name = "Intra-EEA",
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Transactions outside EEA (not subject to interchange caps)",
                            Name = "Inter-Regional",
                            Type = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Region could not be determined",
                            Name = "Unknown",
                            Type = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BinTool.Core.Entities.BinRange", b =>
                {
                    b.HasOne("BinTool.Core.Entities.Country", "Country")
                        .WithMany("BinRanges")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("BinTool.Core.Entities.CommissionRule", b =>
                {
                    b.HasOne("BinTool.Core.Entities.Region", "Region")
                        .WithMany("CommissionRules")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Region");
                });

            modelBuilder.Entity("BinTool.Core.Entities.Country", b =>
                {
                    b.HasOne("BinTool.Core.Entities.Region", "Region")
                        .WithMany("Countries")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BinTool.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BinTool.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BinTool.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BinTool.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BinTool.Core.Entities.Country", b =>
                {
                    b.Navigation("BinRanges");
                });

            modelBuilder.Entity("BinTool.Core.Entities.Region", b =>
                {
                    b.Navigation("CommissionRules");

                    b.Navigation("Countries");
                });
#pragma warning restore 612, 618
        }
    }
}
