// <auto-generated />
using System;
using BinTool.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BinTool.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("BinTool.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111111",
                            ConcurrencyStamp = "11111111-1111-1111-1111-111111111111",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full access: manage BIN ranges, commission rules, users and imports",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "22222222-2222-2222-2222-222222222222",
                            ConcurrencyStamp = "22222222-2222-2222-2222-222222222222",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read-only access: browse BIN ranges, rules and audit history",
                            Name = "Viewer",
                            NormalizedName = "VIEWER"
                        });
                });

            modelBuilder.Entity("BinTool.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ApplicationUser_IsActive");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BinTool.Domain.Entities.AuditEntry", b =>
                {
                    b.Property<int>("AuditEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PerformedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PerformedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.HasKey("AuditEntryId");

                    b.HasIndex("PerformedByUserId")
                        .HasDatabaseName("IX_AuditEntry_UserId");

                    b.HasIndex("EntityType", "PerformedAt")
                        .HasDatabaseName("IX_AuditEntry_Type_Timestamp");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("BinTool.Domain.Entities.BinRange", b =>
                {
                    b.Property<int>("BinRangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardSchemeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("FundingTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrefixLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.HasKey("BinRangeId");

                    b.HasIndex("CardSchemeId");

                    b.HasIndex("CountryId");

                    b.HasIndex("FundingTypeId");

                    b.HasIndex("Prefix")
                        .IsUnique();

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("Prefix", "CardSchemeId")
                        .HasDatabaseName("IX_BinRange_Prefix_Scheme");

                    b.ToTable("BinRanges", (string)null);
                });

            modelBuilder.Entity("BinTool.Domain.Entities.CardScheme", b =>
                {
                    b.Property<int>("CardSchemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CardSchemeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CardSchemes", (string)null);

                    b.HasData(
                        new
                        {
                            CardSchemeId = 1,
                            Description = "Visa card scheme",
                            IsDeleted = false,
                            Name = "Visa"
                        },
                        new
                        {
                            CardSchemeId = 2,
                            Description = "Mastercard and Maestro",
                            IsDeleted = false,
                            Name = "Mastercard"
                        },
                        new
                        {
                            CardSchemeId = 3,
                            Description = "American Express",
                            IsDeleted = false,
                            Name = "American Express"
                        },
                        new
                        {
                            CardSchemeId = 4,
                            Description = "Diners Club",
                            IsDeleted = false,
                            Name = "Diners Club"
                        });
                });

            modelBuilder.Entity("BinTool.Domain.Entities.CommissionRule", b =>
                {
                    b.Property<int>("CommissionRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FixedAmount")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinimumFee")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PercentageRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.HasKey("CommissionRuleId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_CommissionRule_IsActive");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_CommissionRule_Priority");

                    b.ToTable("CommissionRules", (string)null);
                });

            modelBuilder.Entity("BinTool.Domain.Entities.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("CountryId");

                    b.HasIndex("IsoCode")
                        .IsUnique();

                    b.HasIndex("RegionId");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsoCode = "BG",
                            Name = "Bulgaria",
                            RegionId = 1,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CountryId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsoCode = "AT",
                            Name = "Austria",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CountryId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsoCode = "BE",
                            Name = "Belgium",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CountryId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsoCode = "FR",
                            Name = "France",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CountryId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsoCode = "DE",
                            Name = "Germany",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CountryId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsoCode = "IT",
                            Name = "Italy",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CountryId = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsoCode = "ES",
                            Name = "Spain",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CountryId = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsoCode = "NL",
                            Name = "Netherlands",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CountryId = 9,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsoCode = "SE",
                            Name = "Sweden",
                            RegionId = 2,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CountryId = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsoCode = "GB",
                            Name = "United Kingdom",
                            RegionId = 3,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CountryId = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsoCode = "US",
                            Name = "United States",
                            RegionId = 3,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CountryId = 12,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsoCode = "CA",
                            Name = "Canada",
                            RegionId = 3,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CountryId = 13,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsoCode = "JP",
                            Name = "Japan",
                            RegionId = 3,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CountryId = 14,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsoCode = "CN",
                            Name = "China",
                            RegionId = 3,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BinTool.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RateToEur")
                        .HasPrecision(18, 10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("CurrencyId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Currencies", (string)null);

                    b.HasData(
                        new
                        {
                            CurrencyId = 1,
                            Code = "EUR",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Euro",
                            RateToEur = 1m,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CurrencyId = 2,
                            Code = "BGN",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bulgarian lev",
                            RateToEur = 0.5112918788m,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BinTool.Domain.Entities.DefaultRule", b =>
                {
                    b.Property<int>("DefaultRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommissionRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("INTEGER");

                    b.HasKey("DefaultRuleId");

                    b.HasIndex("CommissionRuleId")
                        .IsUnique();

                    b.ToTable("DefaultRules", (string)null);
                });

            modelBuilder.Entity("BinTool.Domain.Entities.FundingType", b =>
                {
                    b.Property<int>("FundingTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("FundingTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FundingTypes", (string)null);

                    b.HasData(
                        new
                        {
                            FundingTypeId = 1,
                            Description = "Credit cards",
                            IsDeleted = false,
                            Name = "Credit"
                        },
                        new
                        {
                            FundingTypeId = 2,
                            Description = "Debit cards",
                            IsDeleted = false,
                            Name = "Debit"
                        });
                });

            modelBuilder.Entity("BinTool.Domain.Entities.ImportHistory", b =>
                {
                    b.Property<int>("ImportHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ImportedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportedRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RejectedRows")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdatedRows")
                        .HasColumnType("INTEGER");

                    b.HasKey("ImportHistoryId");

                    b.HasIndex("ImportedAt")
                        .HasDatabaseName("IX_ImportHistory_Date");

                    b.HasIndex("ImportedByUserId");

                    b.ToTable("ImportHistories", (string)null);
                });

            modelBuilder.Entity("BinTool.Domain.Entities.PendingBinConflict", b =>
                {
                    b.Property<int>("PendingBinConflictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardSchemeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConflictType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("FundingTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportHistoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrefixLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetBinRangeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.HasKey("PendingBinConflictId");

                    b.HasIndex("ImportHistoryId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PendingBinConflict_Status");

                    b.HasIndex("TargetBinRangeId");

                    b.ToTable("PendingBinConflicts", (string)null);
                });

            modelBuilder.Entity("BinTool.Domain.Entities.ProductType", b =>
                {
                    b.Property<int>("ProductTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ProductTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProductTypes", (string)null);

                    b.HasData(
                        new
                        {
                            ProductTypeId = 1,
                            Description = "Consumer cards",
                            IsDeleted = false,
                            Name = "Consumer"
                        },
                        new
                        {
                            ProductTypeId = 2,
                            Description = "Commercial/Business cards",
                            IsDeleted = false,
                            Name = "Commercial"
                        },
                        new
                        {
                            ProductTypeId = 3,
                            Description = "Prepaid cards",
                            IsDeleted = false,
                            Name = "Prepaid"
                        });
                });

            modelBuilder.Entity("BinTool.Domain.Entities.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("RegionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Regions", (string)null);

                    b.HasData(
                        new
                        {
                            RegionId = 1,
                            Description = "Domestic transactions (same country)",
                            IsDeleted = false,
                            Name = "Domestic"
                        },
                        new
                        {
                            RegionId = 2,
                            Description = "Transactions within European Economic Area (subject to interchange caps)",
                            IsDeleted = false,
                            Name = "Intra-EEA"
                        },
                        new
                        {
                            RegionId = 3,
                            Description = "Transactions outside EEA (not subject to interchange caps)",
                            IsDeleted = false,
                            Name = "Inter-Regional"
                        });
                });

            modelBuilder.Entity("BinTool.Domain.Entities.RejectedImportRow", b =>
                {
                    b.Property<int>("RejectedRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportHistoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("RowNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("RejectedRowId");

                    b.HasIndex("ImportHistoryId");

                    b.ToTable("RejectedImportRows", (string)null);
                });

            modelBuilder.Entity("BinTool.Domain.Entities.RuleCriteria", b =>
                {
                    b.Property<int>("RuleCriteriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CardSchemeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommissionRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FundingTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriorityScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RegionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RuleCriteriaId");

                    b.HasIndex("CommissionRuleId");

                    b.HasIndex("FundingTypeId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("RegionId");

                    b.HasIndex("CardSchemeId", "ProductTypeId", "FundingTypeId", "RegionId")
                        .HasDatabaseName("IX_RuleCriteria_Lookup");

                    b.ToTable("RuleCriteria", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BinTool.Domain.Entities.AuditEntry", b =>
                {
                    b.HasOne("BinTool.Domain.Entities.ApplicationUser", "PerformedByUser")
                        .WithMany("AuditEntries")
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("BinTool.Domain.Entities.BinRange", b =>
                {
                    b.HasOne("BinTool.Domain.Entities.CardScheme", "CardScheme")
                        .WithMany("BinRanges")
                        .HasForeignKey("CardSchemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BinTool.Domain.Entities.Country", "Country")
                        .WithMany("BinRanges")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BinTool.Domain.Entities.FundingType", "FundingType")
                        .WithMany("BinRanges")
                        .HasForeignKey("FundingTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BinTool.Domain.Entities.ProductType", "ProductType")
                        .WithMany("BinRanges")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CardScheme");

                    b.Navigation("Country");

                    b.Navigation("FundingType");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("BinTool.Domain.Entities.CommissionRule", b =>
                {
                    b.HasOne("BinTool.Domain.Entities.Currency", "Currency")
                        .WithMany("CommissionRules")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("BinTool.Domain.Entities.Country", b =>
                {
                    b.HasOne("BinTool.Domain.Entities.Region", "Region")
                        .WithMany("Countries")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("BinTool.Domain.Entities.DefaultRule", b =>
                {
                    b.HasOne("BinTool.Domain.Entities.CommissionRule", "CommissionRule")
                        .WithOne("DefaultRule")
                        .HasForeignKey("BinTool.Domain.Entities.DefaultRule", "CommissionRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommissionRule");
                });

            modelBuilder.Entity("BinTool.Domain.Entities.ImportHistory", b =>
                {
                    b.HasOne("BinTool.Domain.Entities.ApplicationUser", "ImportedByUser")
                        .WithMany("Imports")
                        .HasForeignKey("ImportedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ImportedByUser");
                });

            modelBuilder.Entity("BinTool.Domain.Entities.PendingBinConflict", b =>
                {
                    b.HasOne("BinTool.Domain.Entities.ImportHistory", "ImportHistory")
                        .WithMany()
                        .HasForeignKey("ImportHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BinTool.Domain.Entities.BinRange", "TargetBinRange")
                        .WithMany()
                        .HasForeignKey("TargetBinRangeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ImportHistory");

                    b.Navigation("TargetBinRange");
                });

            modelBuilder.Entity("BinTool.Domain.Entities.RejectedImportRow", b =>
                {
                    b.HasOne("BinTool.Domain.Entities.ImportHistory", "ImportHistory")
                        .WithMany("RejectedRows_Navigation")
                        .HasForeignKey("ImportHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportHistory");
                });

            modelBuilder.Entity("BinTool.Domain.Entities.RuleCriteria", b =>
                {
                    b.HasOne("BinTool.Domain.Entities.CardScheme", "CardScheme")
                        .WithMany("RuleCriteria")
                        .HasForeignKey("CardSchemeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BinTool.Domain.Entities.CommissionRule", "CommissionRule")
                        .WithMany("RuleCriteria")
                        .HasForeignKey("CommissionRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BinTool.Domain.Entities.FundingType", "FundingType")
                        .WithMany("RuleCriteria")
                        .HasForeignKey("FundingTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BinTool.Domain.Entities.ProductType", "ProductType")
                        .WithMany("RuleCriteria")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BinTool.Domain.Entities.Region", "Region")
                        .WithMany("RuleCriteria")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CardScheme");

                    b.Navigation("CommissionRule");

                    b.Navigation("FundingType");

                    b.Navigation("ProductType");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("BinTool.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BinTool.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BinTool.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("BinTool.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BinTool.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BinTool.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BinTool.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("AuditEntries");

                    b.Navigation("Imports");
                });

            modelBuilder.Entity("BinTool.Domain.Entities.CardScheme", b =>
                {
                    b.Navigation("BinRanges");

                    b.Navigation("RuleCriteria");
                });

            modelBuilder.Entity("BinTool.Domain.Entities.CommissionRule", b =>
                {
                    b.Navigation("DefaultRule");

                    b.Navigation("RuleCriteria");
                });

            modelBuilder.Entity("BinTool.Domain.Entities.Country", b =>
                {
                    b.Navigation("BinRanges");
                });

            modelBuilder.Entity("BinTool.Domain.Entities.Currency", b =>
                {
                    b.Navigation("CommissionRules");
                });

            modelBuilder.Entity("BinTool.Domain.Entities.FundingType", b =>
                {
                    b.Navigation("BinRanges");

                    b.Navigation("RuleCriteria");
                });

            modelBuilder.Entity("BinTool.Domain.Entities.ImportHistory", b =>
                {
                    b.Navigation("RejectedRows_Navigation");
                });

            modelBuilder.Entity("BinTool.Domain.Entities.ProductType", b =>
                {
                    b.Navigation("BinRanges");

                    b.Navigation("RuleCriteria");
                });

            modelBuilder.Entity("BinTool.Domain.Entities.Region", b =>
                {
                    b.Navigation("Countries");

                    b.Navigation("RuleCriteria");
                });
#pragma warning restore 612, 618
        }
    }
}
